### ISSUE TITLE
Out-of-bounds access when calling barabasi_albert_game with zero vertices

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1138]
Caught when running the IGraph/M test suite with address sanitizer.

Pure C example to follow later.

```
In[2]:= IGBarabasiAlbertGame[0,1]                                                                                                
=================================================================
==76895==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000b6c8 at pc 0x0001161a0af5 bp 0x7ffeec2fdbd0 sp 0x7ffeec2fdbc8
READ of size 8 at 0x60200000b6c8 thread T0
    #0 0x1161a0af4 in igraph_psumtree_update igraph_psumtree.c:83
    #1 0x11600a179 in igraph_i_barabasi_game_psumtree games.c:353
    #2 0x11600abec in igraph_barabasi_game games.c:564
    #3 0x115e513dc in IG::barabasiAlbertGame(long long, double, double, long long, mma::TensorRef<double>, bool, bool, long long) (IGraphM.dylib:x86_64+0x373dc)
    #4 0x115e50f35 in IG_barabasiAlbertGame (IGraphM.dylib:x86_64+0x36f35)
    #5 0x10978464d  (libWolframEngine.dylib:x86_64+0x2c564d)
    ...

0x60200000b6c8 is located 8 bytes to the left of 8-byte region [0x60200000b6d0,0x60200000b6d8)
allocated by thread T0 here:
    #0 0x103960497 in wrap_calloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x57497)
    #1 0x1160eb24d in igraph_vector_init vector.pmt:128
    #2 0x1161a0869 in igraph_psumtree_init igraph_psumtree.c:41
    #3 0x116009f5c in igraph_i_barabasi_game_psumtree games.c:336
    #4 0x11600abec in igraph_barabasi_game games.c:564
    #5 0x115e513dc in IG::barabasiAlbertGame(long long, double, double, long long, mma::TensorRef<double>, bool, bool, long long) (IGraphM.dylib:x86_64+0x373dc)
    #6 0x115e50f35 in IG_barabasiAlbertGame (IGraphM.dylib:x86_64+0x36f35)
    #7 0x10978464d  (libWolframEngine.dylib:x86_64+0x2c564d)
    ...

SUMMARY: AddressSanitizer: heap-buffer-overflow igraph_psumtree.c:83 in igraph_psumtree_update
Shadow bytes around the buggy address:
  0x1c0400001680: fa fa 00 fa fa fa fd fa fa fa 00 04 fa fa 00 fa
  0x1c0400001690: fa fa fd fa fa fa 00 04 fa fa 00 fa fa fa fd fa
  0x1c04000016a0: fa fa 00 04 fa fa 00 fa fa fa 01 fa fa fa fd fd
  0x1c04000016b0: fa fa fd fa fa fa fd fd fa fa 00 fa fa fa fd fa
  0x1c04000016c0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x1c04000016d0: fa fa fd fa fa fa 00 fa fa[fa]00 fa fa fa 00 fa
  0x1c04000016e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c04000016f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400001700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400001710: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400001720: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb

Out[2]= Graph[<0>, <0>]

In[3]:= Options[IGBarabasiAlbertGame]                                                                                            

Out[3]= {DirectedEdges -> True, TotalDegreeAttraction -> False, Method -> PSumTree, StartingGraph -> None}

In[4]:=         
```

**Comment by ntamas** [comment]
Hmm, what shall we do when the user passes `n=0` and `m>0`? Shall we create a graph with `m` loop edges, or shall we simply throw an error?

**Comment by szhorvat** [comment]
I checked a number of different cases where `m>n`, including when `m` is different for each step (i.e. using the `outseq` parameter). The problem is only present for `n=0`. However, for `n=0`, there's a problem for all three available methods (even for `IGRAPH_BARABASI_BAG`).

I suggest adding a check for `n=0` before calling any of the specific methods.

**Comment by szhorvat** [comment]
PR sent.
