### ISSUE TITLE
GraphML reader mishandles finally stack

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1911]
**Describe the bug**

The GraphML reader crashes on the attached example with:

```
Fatal error at src/core/error.c:256 : Corrupt finally stack: trying to pop 3 element(s) when only 0 left.
```

**To reproduce**

[bug.graphml.zip](https://github.com/igraph/igraph/files/7807726/bug.graphml.zip)

```
Stack trace:
    #0 0x1046a2405 in __sanitizer_print_stack_trace+0x35 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4f405)
    #1 0x103fd8b71 in igraph_abort error.c:69
    #2 0x103fd8b12 in igraph_fatal error.c
    #3 0x103fd8585 in igraph_fatalf error.c:388
    #4 0x103fd8636 in IGRAPH_FINALLY_CLEAN error.c:256
    #5 0x10412d57b in igraph_i_graphml_sax_handler_end_document graphml.c:524
    #6 0x10442ad9a in xmlParseChunk+0x549 (libxml2.2.dylib:x86_64+0x1ad9a)
    #7 0x104120b2a in igraph_read_graph_graphml graphml.c:1407
    #8 0x103fd7734 in LLVMFuzzerTestOneInput xx.cpp:55
    #9 0x10415c210 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:611
    #10 0x10415b74a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) FuzzerLoop.cpp:514
    #11 0x10415d0e8 in fuzzer::Fuzzer::MutateAndTestOne() FuzzerLoop.cpp:757
    #12 0x10415dc85 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) FuzzerLoop.cpp:895
    #13 0x10414b524 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:906
    #14 0x104178892 in main FuzzerMain.cpp:20
    #15 0x7fff5a3b03d4 in start+0x0 (libdyld.dylib:x86_64+0x163d4)

==63002== ERROR: libFuzzer: deadly signal
    #0 0x1046a2405 in __sanitizer_print_stack_trace+0x35 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4f405)
    #1 0x1041773e8 in fuzzer::PrintStackTrace() FuzzerUtil.cpp:210
    #2 0x10415a9d3 in fuzzer::Fuzzer::CrashCallback() FuzzerLoop.cpp:233
    #3 0x7fff5a59bb5c in _sigtramp+0x1c (libsystem_platform.dylib:x86_64+0x4b5c)
    #4 0x1042a2d3f in igraph_i_fatal_handler+0x1f (igraph_test:x86_64+0x1002ced3f)
    #5 0x7fff5a4556a5 in abort+0x7e (libsystem_c.dylib:x86_64+0x5b6a5)
    #6 0x103fd8b7b in igraph_abort error.c:71
    #7 0x103fd8b12 in igraph_fatal error.c
    #8 0x103fd8585 in igraph_fatalf error.c:388
    #9 0x103fd8636 in IGRAPH_FINALLY_CLEAN error.c:256
    #10 0x10412d57b in igraph_i_graphml_sax_handler_end_document graphml.c:524
    #11 0x10442ad9a in xmlParseChunk+0x549 (libxml2.2.dylib:x86_64+0x1ad9a)
    #12 0x104120b2a in igraph_read_graph_graphml graphml.c:1407
    #13 0x103fd7734 in LLVMFuzzerTestOneInput xx.cpp:55
    #14 0x10415c210 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:611
    #15 0x10415b74a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) FuzzerLoop.cpp:514
    #16 0x10415d0e8 in fuzzer::Fuzzer::MutateAndTestOne() FuzzerLoop.cpp:757
    #17 0x10415dc85 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) FuzzerLoop.cpp:895
    #18 0x10414b524 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:906
    #19 0x104178892 in main FuzzerMain.cpp:20
    #20 0x7fff5a3b03d4 in start+0x0 (libdyld.dylib:x86_64+0x163d4)
```

**Version information**
`develop`

**Comment by szhorvat** [comment]
I'm also getting:

```
Warning at src/io/graphml.c:654 : Ignoring <key id="d2"> because of a missing or unknown 'attr.type' attribute
Warning at src/io/graphml.c:911 : state->current_attr_record was null where it should have been non-null; this is probably a bug. Please notify the developers!
Warning at src/io/graphml.c:654 : Ignoring <key id="d2"> because of a missing or unknown 'attr.type' attribute
Warning at src/io/graphml.c:911 : state->current_attr_record was null where it should have been non-null; this is probably a bug. Please notify the developers!
```

These should be made into fatal errors, not warnings, otherwise we'll never get a report. These problems should cause test failures, including on OSS-fuzz, which won't happen either with an warning or a normal error.

**Comment by ntamas** [comment]
The GraphML parser now crashes after the first warning; we still need to handle this properly, though.

**Comment by ntamas** [comment]
I think this is now fixed in 21a279dc ; let's wait for the CI first.

**Comment by ntamas** [comment]
@szhorvat Note that the GraphML file in the ZIP is actually not an invalid XML file - it passes standard XML validation checks. Sure, it is not valid GraphML because some tags appear in places where they shouldn't, and some attributes are present on tags that should not be there, but 1) we could not conclude that without performing a full DTD validation of the XML file, which is outside the scope of igraph, and 2) it is probably better to be lenient in what we accept in case people throw slightly misformatted GraphML files at igraph. So, the fact that the GraphML file is parsed and accepted by our test case is not an error. Shall we relax the requirements in the `igraph_read_graph_graphml_invalid_inputs` test so that we don't fail the test if we manage to parse this file and create a graph out of it?

**Comment by szhorvat** [comment]
This looks fixed, so closing. There are memory leaks, I'll open a new issue for that.

Regarding being lenient with validation: **absolutely!** There are a lot of GraphML files in the wild that won't validate, yet many systems will happily read them. So should igraph.

What I was referring to above was this warning:

```
Warning at src/io/graphml.c:911 : state->current_attr_record was null where it should have been non-null; this is probably a bug. Please notify the developers!
```

This is not a useful warning. If it indicates a bug in igraph, it should be a fatal error, so that tests/fuzzers can find the bug. If there is no bug, there should be no cryptic warning message referencing internals (and pointers of all things!)
