### ISSUE TITLE
Memory leaks in GraphML reader

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1912]
**Describe the bug**
There are still some memory leaks in the GraphML reader. I am attaching examples that trigger them. Compile with the leak sanitizer (`-fsanitize=leak`) to see them.

Note that on my macOS 10.14 system, the leak sanitizer does not seem to be available with Xcode's clang. I use Clang 13.0 from MacPorts. With this compiler, the leak sanitizer seems to work, but only if the address sanitizer is not enabled. Not sure why.

**To reproduce**

[graphml-leaks.zip](https://github.com/igraph/igraph/files/7810559/graphml-leaks.zip)

Some example leaks:

```
==80557==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2 byte(s) in 2 object(s) allocated from:
    #0 0x10c837b88 in wrap_malloc+0x58 (libclang_rt.lsan_osx_dynamic.dylib:x86_64h+0x8b88)
    #1 0x7fff5a452c03 in strdup+0x1f (libsystem_c.dylib:x86_64+0x58c03)
    #2 0x10c3b38f9 in igraph_i_graphml_add_attribute_key graphml.c:565
    #3 0x10c3b25fb in igraph_i_graphml_sax_handler_start_element_ns graphml.c:1014
    #4 0x10c608fcc in xmlParseStartTag2+0xf69 (libxml2.2.dylib:x86_64+0x1ffcc)
    #5 0x10c604b8c in xmlParseTryOrFinish+0xd83 (libxml2.2.dylib:x86_64+0x1bb8c)
    #6 0x10c603ae5 in xmlParseChunk+0x294 (libxml2.2.dylib:x86_64+0x1aae5)
    #7 0x10c3a7a42 in igraph_read_graph_graphml graphml.c:1401
    #8 0x10c3166e3 in LLVMFuzzerTestOneInput xx.cpp:54
    #9 0x10c3d29c0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:611
    #10 0x10c3d1efa in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) FuzzerLoop.cpp:514
    #11 0x10c3d3898 in fuzzer::Fuzzer::MutateAndTestOne() FuzzerLoop.cpp:757
    #12 0x10c3d4435 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) FuzzerLoop.cpp:895
    #13 0x10c3c1cd4 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:906
    #14 0x10c3ef042 in main FuzzerMain.cpp:20
    #15 0x7fff5a3b03d4 in start+0x0 (libdyld.dylib:x86_64+0x163d4)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x10c837b88 in wrap_malloc+0x58 (libclang_rt.lsan_osx_dynamic.dylib:x86_64h+0x8b88)
    #1 0x7fff5a452c03 in strdup+0x1f (libsystem_c.dylib:x86_64+0x58c03)
    #2 0x10c3b38f9 in igraph_i_graphml_add_attribute_key graphml.c:565
    #3 0x10c3b25fb in igraph_i_graphml_sax_handler_start_element_ns graphml.c:1014
    #4 0x10c608fcc in xmlParseStartTag2+0xf69 (libxml2.2.dylib:x86_64+0x1ffcc)
    #5 0x10c604b8c in xmlParseTryOrFinish+0xd83 (libxml2.2.dylib:x86_64+0x1bb8c)
    #6 0x10c603ae5 in xmlParseChunk+0x294 (libxml2.2.dylib:x86_64+0x1aae5)
    #7 0x10c3a79f1 in igraph_read_graph_graphml graphml.c:1396
    #8 0x10c3166e3 in LLVMFuzzerTestOneInput xx.cpp:54
    #9 0x10c3d29c0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:611
    #10 0x10c3d1efa in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) FuzzerLoop.cpp:514
    #11 0x10c3d3898 in fuzzer::Fuzzer::MutateAndTestOne() FuzzerLoop.cpp:757
    #12 0x10c3d4435 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) FuzzerLoop.cpp:895
    #13 0x10c3c1cd4 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:906
    #14 0x10c3ef042 in main FuzzerMain.cpp:20
    #15 0x7fff5a3b03d4 in start+0x0 (libdyld.dylib:x86_64+0x163d4)
```

**Version information**

I tested this in `master` this time, as you're working there first @ntamas.

**Comment by ntamas** [comment]
It seems like all the leaks originate from an `strdup()` call in `igraph_i_graphml_add_attribute_key`, `graphml.c`, line 565. I have tried to address this in 66eedb308 ; let me know whether it worked.
