### ISSUE TITLE
Error: igraph.drawing.cairo.plot.cairo.MemoryError: out of memory

### ISSUE THREAD

**Issue by BaseMax** [igraph/igraph#2230]
**Describe the bug**

```
Traceback (most recent call last):
  File "C:\Users\Max\Desktop\graphs-generation\graphs.py", line 40, in <module>
    igraph.plot(g, target='myfile.pdf')
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\__init__.py", line 284, in plot
    result.save()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\cairo\plot.py", line 317, in save
    self._ctx.show_page()
igraph.drawing.cairo.plot.cairo.MemoryError: out of memory
```

**To reproduce**

```
import igraph
import matplotlib.pyplot as plt

print(igraph.__version__)
m1 = [
    [1, 2, 3, 4, 5, 7, 6],
    [1, 2, 3, 5, 4, 6, 7],
    [1, 2, 4, 3, 5, 6, 7],
    [1, 2, 5, 4, 3, 6, 7],
    [2, 1, 3, 4, 5, 6, 7],
    [6, 7, 3, 4, 5, 1, 2],
    [7, 6, 3, 4, 5, 2, 1],
]
g = igraph.Graph.Adjacency(m1)
print(g)
print(g.get_adjacency())
igraph.plot(g, target='myfile.pdf')
```

**Version information**
0.10.1

**Comment by ntamas** [comment]
Closing this as it affects the Python interface only; discussion continues in https://github.com/igraph/python-igraph/issues/588
