### ISSUE TITLE
Crash in `igraph_sparsemat_as_matrix()` with all-zero matrix

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2500]
**Describe the bug**

There is a crash in `igraph_i_sparsemat_as_matrix_cc()` when passing a compressed-format sparse matrix with no non-zero entry to `igraph_sparsemat_as_matrix()`.

**To reproduce**

WIP! Need more time, found with fuzzer whose input was a 10-vertex graph with no edges. The graph was converted to a sparse adjacency matrix, that matrix was compressed, transposed, then converted to a dense matrix.

**Version information**
`master`

**Comment by szhorvat** [comment]
The crash probably happens in the inner `while` condition:

https://github.com/igraph/igraph/blob/4cd597feab0e00d8fc4b1453d18a8a511457e2e5/src/core/sparsemat.c#L2160-L2169

```
==13023==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6080000009f8 at pc 0x000102201aa4 bp 0x00016dc967f0 sp 0x00016dc967e8
READ of size 8 at 0x6080000009f8 thread T0
    #0 0x102201aa0 in igraph_i_sparsemat_as_matrix_cc sparsemat.c:2161
    #1 0x102201664 in igraph_sparsemat_as_matrix sparsemat.c:2213
    #2 0x10216cbd0 in LLVMFuzzerTestOneInput matrices.cpp:67
    #3 0x10235d0b4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:614
    #4 0x10235c9a4 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) FuzzerLoop.cpp:516
    #5 0x10235e748 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&) FuzzerLoop.cpp:812
    #6 0x10235ebc4 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&) FuzzerLoop.cpp:867
    #7 0x10234f930 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:911
    #8 0x1023780e8 in main FuzzerMain.cpp:20
    #9 0x182f810dc  (<unknown module>)
    #10 0x252ffffffffffffc  (<unknown module>)
```
