### ISSUE TITLE
CI fails when using ASan and running on Ubuntu 22.04

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2534]
The CI tests fail when using ASan and running on `ubuntu-22.04`. Currently, `ubuntu-latest` is 22.04 on Azure.

I temporarily reverted to 20.04 until we fix this.

There might be two issues:

Running `arithchk`:

```
[111/2019] Generating arith.h for f2c...
FAILED: vendor/f2c/arith.h /home/vsts/work/1/s/build/vendor/f2c/arith.h 
cd /home/vsts/work/1/s/build/vendor/f2c && /home/vsts/work/1/s/build/vendor/f2c/arithchk > /home/vsts/work/1/s/build/vendor/f2c/arith.h
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
Segmentation fault (core dumped)
```

I could not reproduce this in the `ubuntu:jammy` Docker image.

And we have a likely false positive from LeakSanitizer:

```
360/561 Test #360: test::igraph_power_law_fit..........................***Failed    0.67 sec

=================================================================
==47392==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 192 byte(s) in 1 object(s) allocated from:
    #0 0xffff97c3a2f4 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0xffff978ac460  (/lib/aarch64-linux-gnu/libgomp.so.1+0xc460)
    #2 0xffff978bb95c  (/lib/aarch64-linux-gnu/libgomp.so.1+0x1b95c)
    #3 0xffff978b3aac in GOMP_parallel (/lib/aarch64-linux-gnu/libgomp.so.1+0x13aac)
    #4 0xaaaad5218bb4 in plfit_continuous (/igraph/build/tests/test_igraph_power_law_fit+0x3f8bb4)
    #5 0xaaaad52110b4 in igraph_power_law_fit (/igraph/build/tests/test_igraph_power_law_fit+0x3f10b4)
    #6 0xaaaad5138c30 in test_continuous (/igraph/build/tests/test_igraph_power_law_fit+0x318c30)
    #7 0xaaaad51309c4 in main (/igraph/build/tests/test_igraph_power_law_fit+0x3109c4)
    #8 0xffff96e373f8  (/lib/aarch64-linux-gnu/libc.so.6+0x273f8)
    #9 0xffff96e374c8 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274c8)
    #10 0xaaaad5132dec in _start (/igraph/build/tests/test_igraph_power_law_fit+0x312dec)

SUMMARY: AddressSanitizer: 192 byte(s) leaked in 1 allocation(s).
Test exited abnormally with error: 1
=========================================
CMake Error at /igraph/etc/cmake/run_legacy_test.cmake:32 (message):
  Exiting test.
```

This should be fixable using a suppression file: https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#suppressions

**Comment by ntamas** [comment]
We should probably wait until https://github.com/actions/runner-images/issues/9524 is sorted out.

**Comment by ntamas** [comment]
https://github.com/actions/runner-images/issues/9491 is now closed but I've noticed that the problem was reported by Azure Pipelines and not by Github Actions, so I'm not sure whether the Azure image was also updated. I'll try and then revert if needed.

**Comment by ntamas** [comment]
Seems OK now - the Linux builds have passed.
