### ISSUE TITLE
Finally stack mismatch in `write_all_gml` fuzzer on `develop`

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2557]
**Describe the bug**

There's a finally stack mismatch in the write_all_gml fuzzer on `develop` only (not `master`)

**To reproduce**

[testcase.gz](https://github.com/igraph/igraph/files/14848024/testcase.gz)

**Version information**
Current `develop`

**Comment by szhorvat** [comment]
Can you have a look, @ntamas, and open a PR for the fix so we can make use the ClusterFuzzLite infrastructure (which only runs on PRs)?

Instructions for running fuzzers locally are at https://github.com/igraph/igraph/wiki/Fuzzing

**Comment by ntamas** [comment]
Cannot reproduce this on my machine with the attached test case. I copied the `write_all_gml` fuzzer, modified it to load the attached test case as its input, turned `IGRAPH_VERIFY_FINALLY_STACK` on, and no errors popped up.

**Comment by szhorvat** [comment]
Did you do it on `develop`? The error is only present on `develop`, not `master`.

```
~/R/i/i/build (develop|✔) $ fuzzing/fuzzer_write_all_gml testcase
fuzzer_write_all_gml(74222,0x1fcc83ac0) malloc: nano zone abandoned due to inability to reserve vm space.
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1994940109
INFO: Loaded 1 modules   (13473 inline 8-bit counters): 13473 [0x1024eb908, 0x1024eeda9), 
INFO: Loaded 1 PC tables (13473 PCs): 13473 [0x1024eedb0,0x1025237c0), 
fuzzing/fuzzer_write_all_gml: Running 1 inputs 1 time(s) each.
Running: testcase
Fatal error at /Users/szhorvat/Repos/igraph-main/igraph/fuzzing/write_all_gml.cpp:131 : Assertion failed: IGRAPH_FINALLY_STACK_EMPTY

Stack trace:
    #0 0x10373c64c in __sanitizer_print_stack_trace+0x28 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x5c64c)
    #1 0x1023151f4 in igraph_abort error.c:69
    #2 0x102316be8 in igraph_fatal_handler_abort error.c:428
    #3 0x10231640c in igraph_fatal error.c:437
    #4 0x1023111a8 in LLVMFuzzerTestOneInput write_all_gml.cpp:131
    #5 0x102491788 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:614
    #6 0x10247f2dc in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) FuzzerDriver.cpp:327
    #7 0x1024842cc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:862
    #8 0x1024ac620 in main FuzzerMain.cpp:20
    #9 0x194bee0dc  (<unknown module>)
    #10 0x4c23fffffffffffc  (<unknown module>)

==74222== ERROR: libFuzzer: deadly signal
    #0 0x10373c64c in __sanitizer_print_stack_trace+0x28 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x5c64c)
    #1 0x1024abc14 in fuzzer::PrintStackTrace() FuzzerUtil.cpp:210
    #2 0x102490344 in fuzzer::Fuzzer::CrashCallback() FuzzerLoop.cpp:231
    #3 0x194fa7580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0xd851800194f76c1c  (<unknown module>)
    #5 0xb2f800194e83a1c  (<unknown module>)
    #6 0xb3c8001023151fc  (<unknown module>)
    #7 0x102316be8 in igraph_fatal_handler_abort error.c:428
    #8 0x10231640c in igraph_fatal error.c:437
    #9 0x1023111a8 in LLVMFuzzerTestOneInput write_all_gml.cpp:131
    #10 0x102491788 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:614
    #11 0x10247f2dc in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) FuzzerDriver.cpp:327
    #12 0x1024842cc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:862
    #13 0x1024ac620 in main FuzzerMain.cpp:20
    #14 0x194bee0dc  (<unknown module>)
    #15 0x4c23fffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```

**Comment by szhorvat** [comment]
I first noticed it here: https://github.com/igraph/igraph/actions/runs/8534233930/job/23378263866?pr=2550

**Comment by szhorvat** [comment]
The problem is in the LGL reader (or some code it calls, such as the attribute handler). The attached auto-minimized test case reproduces the problem with the `read_lgl` fuzzer.

[test.lgl.gz](https://github.com/igraph/igraph/files/14856904/test.lgl.gz)
