### ISSUE TITLE
Codecov CI failing

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2712]
The Codecov CI is currently failing. Is there any chance you can have a look at this @ntamas ? The problem may or may not be these semicolons:

https://github.com/igraph/igraph/blob/b25eda2dba6ccbcf5a47fe1cb77796a7f0f524d4/etc/cmake/CodeCoverage.cmake#L346-L356

**Comment by szhorvat** [comment]
May be the same issue reported at https://github.com/bilke/cmake-modules/issues/89

**Comment by szhorvat** [comment]
@ntamas Can you please help a bit with this when you have the time? I updated `CodeCoverage.cmake` and applied the patch from the mentioned PR, but now there are some problems with the exclusions specified here:

https://github.com/igraph/igraph/blob/622f331dc9249b050bc6afbad2032e2c4e78de9e/CMakeLists.txt#L139-L147

On the CI, including `"io/parsers/*"` causes a failure. On my local machine, omitting it causes a failure.

I guess we can try reverting the update to `CodeCoverage.cmake` and _only_ apply the CMake 3.31 compatibility patch, but eventually this will likely need a proper fix.

I'm out of ideas.

**Comment by ntamas** [comment]
[This example] shows that we don't actually need to generate the coverage report with `lcov` in CI, it is enough to run the tests to generate the `*.gcno` and `*.gcda` files and the Codecov uploader will only care about these. So we can set up the target in a way that works for your machine and simply run the unit tests in CI instead of the `coverage` target. That's one thing.

The other thing is that we can switch from `lcov` to `gcovr` and/or `fastcov` (which also uses `gcovr` under the hood if I am not mistaken). I tested `gcovr` and it worked just fine for me with this patch:

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 369a574f5..d09e28a92 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -136,14 +136,14 @@ option(IGRAPH_ENABLE_CODE_COVERAGE "Enable code coverage calculation" OFF)
 if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME AND IGRAPH_ENABLE_CODE_COVERAGE)
   include(CodeCoverage)
   append_coverage_compiler_flags()
-  setup_target_for_coverage_lcov(
+  setup_target_for_coverage_gcovr_html(
     NAME coverage
     EXECUTABLE "${CMAKE_COMMAND}" "--build" "${PROJECT_BINARY_DIR}" "--target" "check"
     # Generated files are excluded; apparently the CodeCoverage script has some
     # problems with them. Yes, the exclusion is correct, it refers to a nonexistent
     # directory that somehow gets into the coverage results. /Applications and
     # /Library/Developer are for macOS -- they exclude files from the macOS SDK.
-    EXCLUDE "src/io/parsers/*" "io/parsers/*" "/Applications/Xcode*" "/Library/Developer/*" "examples/*" "interfaces/*" "tests/*" "vendor/pcg/*"
+    EXCLUDE "build/src/io/parsers/*" "src/io/parsers/*" "io/parsers/*" "/Applications/Xcode*" "/Library/Developer/*" "examples/*" "interfaces/*" "tests/*" "vendor/pcg/*"
   )
 endif()
 ```

What do you think?

**Comment by szhorvat** [comment]
I seem to be getting this error when using gcovr. Are you not seeing the same?

```
(INFO) Reading coverage data...
(ERROR) GCOV produced the following errors processing /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/ncol-lexer.c.gcda:
	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/.:
io/parsers/ncol-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/.:
io/parsers/ncol-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph:
io/parsers/ncol-lexer.c: No such file or directory

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
```

**Comment by szhorvat** [comment]
> [This example](https://github.com/codecov/example-c/blob/main/.github/workflows/ci.yml) shows that we don't actually need to generate the coverage report with `lcov` in CI, it is enough to run the tests to generate the `*.gcno` and `*.gcda` files and the Codecov uploader will only care about these.

I change the `coverage` target to `check` now.

**Comment by ntamas** [comment]
> I seem to be getting this error when using gcovr. Are you not seeing the same?

No, but you might need to remve any old `.gcda` and `.gcno` files from the build dir.

**Comment by szhorvat** [comment]
I am working on a clean current `master` with the patch you proposed. Here's a transcript. Do you spot any difference from yours?

```
~/R/i/igraph (master|✚1) $ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 369a574f5..d09e28a92 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -136,14 +136,14 @@ option(IGRAPH_ENABLE_CODE_COVERAGE "Enable code coverage calculation" OFF)
 if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME AND IGRAPH_ENABLE_CODE_COVERAGE)
   include(CodeCoverage)
   append_coverage_compiler_flags()
-  setup_target_for_coverage_lcov(
+  setup_target_for_coverage_gcovr_html(
     NAME coverage
     EXECUTABLE "${CMAKE_COMMAND}" "--build" "${PROJECT_BINARY_DIR}" "--target" "check"
     # Generated files are excluded; apparently the CodeCoverage script has some
     # problems with them. Yes, the exclusion is correct, it refers to a nonexistent
     # directory that somehow gets into the coverage results. /Applications and
     # /Library/Developer are for macOS -- they exclude files from the macOS SDK.
-    EXCLUDE "src/io/parsers/*" "io/parsers/*" "/Applications/Xcode*" "/Library/Developer/*" "examples/*" "interfaces/*" "tests/*" "vendor/pcg/*"
+    EXCLUDE "build/src/io/parsers/*" "src/io/parsers/*" "io/parsers/*" "/Applications/Xcode*" "/Library/Developer/*" "examples/*" "interfaces/*" "tests/*" "vendor/pcg/*"
   )
 endif()
 
~/R/i/igraph (master|✚1) $ mkdir build && cd build
~/R/i/i/build (master|✚1) $ cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DIGRAPH_ENABLE_CODE_COVERAGE=ON -DFLEX_KEEP_LINE_NUMBERS=ON
-- Version number from Git: 0.10.15-48-g2ab6b8794
-- The C compiler identification is AppleClang 16.0.0.16000026
-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_UNKNOWN_WARNING_OPTION_FLAG
-- Performing Test COMPILER_SUPPORTS_UNKNOWN_WARNING_OPTION_FLAG - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ENUMVAL_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ENUMVAL_ATTR - Success
-- Thread-local storage: supported (__thread)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found FLEX: /opt/local/bin/flex (found version "2.6.4")
-- Found BISON: /opt/local/bin/bison (found version "3.8.2")
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for _stricmp
-- Looking for _stricmp - not found
-- Looking for _strnicmp
-- Looking for _strnicmp - not found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for include file xlocale.h
-- Looking for include file xlocale.h - found
-- Looking for uselocale
-- Looking for uselocale - found
-- Looking for _configthreadlocale
-- Looking for _configthreadlocale - not found
-- Performing Test HAVE__UMUL128
-- Performing Test HAVE__UMUL128 - Failed
-- Performing Test HAVE___UMULH
-- Performing Test HAVE___UMULH - Failed
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of __uint128_t
-- Check size of __uint128_t - done
-- Performing Test HAVE__POPCNT64
-- Performing Test HAVE__POPCNT64 - Failed
-- Performing Test HAVE__POPCNT
-- Performing Test HAVE__POPCNT - Failed
-- Performing Test HAVE__BITSCANFORWARD64
-- Performing Test HAVE__BITSCANFORWARD64 - Failed
-- Performing Test HAVE__BITSCANFORWARD
-- Performing Test HAVE__BITSCANFORWARD - Failed
-- Performing Test HAVE__BITSCANREVERSE64
-- Performing Test HAVE__BITSCANREVERSE64 - Failed
-- Performing Test HAVE__BITSCANREVERSE
-- Performing Test HAVE__BITSCANREVERSE - Failed
-- Performing Test HAVE_BUILTIN_OVERFLOW
-- Performing Test HAVE_BUILTIN_OVERFLOW - Success
-- Performing Test HAVE_cxx_fprofile_abs_path
-- Performing Test HAVE_cxx_fprofile_abs_path - Failed
-- Performing Test HAVE_c_fprofile_abs_path
-- Performing Test HAVE_c_fprofile_abs_path - Failed
-- Appending code coverage compiler flags: -g --coverage
-- Looking for _LIBCPP_VERSION
-- Looking for _LIBCPP_VERSION - found
-- Looking for __GLIBCXX__
-- Looking for __GLIBCXX__ - not found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Performing Test HAVE_ENABLE_NEW_DTAGS
-- Performing Test HAVE_ENABLE_NEW_DTAGS - Failed
-- Found Python3: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (found version "3.9.6") found components: Interpreter
--  
-- -----[ Build configuration ]----
-- Version:   0.10.15-48-g2ab6b8794
-- CMake build type:          Debug
-- Library type:             static
-- igraph_integer_t size:   64 bits
-- Compiler cache:           ccache
--  
-- ----------[ Features ]----------
-- GLPK for optimization:       yes
-- Reading GraphML files:       yes
-- Thread-local storage:        yes
-- Link-time optimization:       no
--  
-- --------[ Dependencies ]--------
-- ARPACK:                      yes
-- BISON:                       yes
-- BLAS:                        yes
-- FLEX:                        yes
-- GLPK:                        yes
-- GMP:                         yes
-- LAPACK:                      yes
-- LibXml2:                     yes
-- OpenMP:                       no
-- PLFIT:                       yes
--  
-- -----------[ Testing ]----------
-- Diff tool:                  diff
-- Sanitizers:                 none
-- Code coverage:               yes
-- Verify 'finally' stack:       no
--  
-- --------[ Documentation ]-------
-- HTML:                        yes
-- PDF:                         yes
-- INFO:                         no
--  
-- igraph configured successfully.
--  
-- Configuring done (9.2s)
make -j12 coverage-- Generating done (4.2s)
-- Build files have been written to: /Users/szhorvat/Repos/igraph-main/igraph/build
~/R/i/i/build (master|✚1) $ make -j12 coverage
Running gcovr to produce HTML code coverage report.
make[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  0%] Building CXX object src/isomorphism/bliss/CMakeFiles/bliss.dir/defs.cc.o
[  0%] Building CXX object src/isomorphism/bliss/CMakeFiles/bliss.dir/graph.cc.o
[  0%] Building CXX object src/isomorphism/bliss/CMakeFiles/bliss.dir/heap.cc.o
[  0%] Building CXX object src/isomorphism/bliss/CMakeFiles/bliss.dir/orbit.cc.o

...
...
...

[100%] Built target test_jdm
[100%] Built target build_tests
[100%] Executing unit tests...
Test project /Users/szhorvat/Repos/igraph-main/igraph/build/tests
570/570 Test #445: test::igraph_community_infomap
100% tests passed, 0 tests failed out of 570

Total Test time (real) =  24.96 sec
[100%] Built target check
(INFO) Reading coverage data...
(WARNING) LCOV_EXCL_LINE found on line 269 in excluded region started on line 264, when processing /Users/szhorvat/Repos/igraph-main/igraph/src/core/strvector.c.
(ERROR) GCOV produced the following errors processing /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/pajek-lexer.c.gcda:
	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph:
io/parsers/pajek-lexer.c: No such file or directory

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 597, in process_datafile
    raise RuntimeError(errors_output)
RuntimeError: GCOV produced the following errors processing /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/pajek-lexer.c.gcda:
	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph:
io/parsers/pajek-lexer.c: No such file or directory

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 597, in process_datafile
    raise RuntimeError(errors_output)
RuntimeError: GCOV produced the following errors processing /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/pajek-lexer.c.gcda:
	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph:
io/parsers/pajek-lexer.c: No such file or directory

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/__main__.py", line 358, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/__init__.py", line 85, in read_reports
    covdata = GcovHandler(options).read_report()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/__init__.py", line 215, in read_report
    return read_report(self.options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 96, in read_report
    with Workers(
         ~~~~~~~^
        options.gcov_parallel,
        ^^^^^^^^^^^^^^^^^^^^^^
        lambda: {"covdata": dict(), "to_erase": set(), "options": options},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as pool:
    ^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 177, in __exit__
    self.wait()
    ~~~~~~~~~^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 103, in read_report
    contexts = pool.wait()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 597, in process_datafile
    raise RuntimeError(errors_output)
RuntimeError: GCOV produced the following errors processing /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/pajek-lexer.c.gcda:
	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph:
io/parsers/pajek-lexer.c: No such file or directory

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.

GCOV produced the following errors processing /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/pajek-lexer.c.gcda:
	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/src/CMakeFiles/igraph.dir/io/parsers/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph/build/.:
io/parsers/pajek-lexer.c: No such file or directory

	In directory /Users/szhorvat/Repos/igraph-main/igraph:
io/parsers/pajek-lexer.c: No such file or directory

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
make[3]: *** [CMakeFiles/coverage] Error 64
make[2]: *** [CMakeFiles/coverage.dir/all] Error 2
make[1]: *** [CMakeFiles/coverage.dir/rule] Error 2
make: *** [coverage] Error 2
~/R/i/i/build (master|✚1) [2] $ gcovr --version
gcovr 8.2

Copyright (c) 2013-2024 the gcovr authors
Copyright (c) 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
~/R/i/i/build (master|✚1) $ gcov --version
Apple LLVM version 16.0.0
   (clang-1600.0.26.6)Optimized build.
~/R/i/i/build (master|✚1) $ 
```

**Comment by ntamas** [comment]
I was using Ninja and it worked with Ninja when `FLEX_KEEP_LINE_NUMBERS` was off. It failed with some parse errors (`TypeError: sequence item 1: expected str instance, list found`) when it was on, but this is different from what you saw. I guess the key difference is Ninja vs `make`.

**Comment by szhorvat** [comment]
I remember that coverage reports couldn't be generated in the past with Ninja, only make, but I don't recall why. We have a note in the wiki.

It does indeed work with Ninja for me now, which is fine by me.

Even though the Codecov action runs now, coverage dropped from 83% to 75%. I'm not sure why. I'm giving up on this for the moment. I'm happy to have passing CI and I'll focus on handling the outstanding PRs now.

**Comment by szhorvat** [comment]
I can't get this working properly for my life ...
