### ISSUE TITLE
"from igraph._igraph import" fails

### ISSUE THREAD

**Issue by VladimirAlexiev** [igraph/igraph#581]
I build and install igraph and interfaces/python from this git repo. Then I'm trying to use this program: https://github.com/specgen/specgen. I get this error:
```
File "./specgen6.py", line 51, in <module>
    from libgroups import Grouping
  File "/cygdrive/c/prog/specgen/libgroups.py", line 25, in <module>
    from igraph import *
  File "/usr/lib/python2.7/site-packages/python_igraph-0.6.6-py2.7-cygwin-1.7.28-x86_64.egg/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
```
I got a similar error when trying to use the "official" stable version 0.6.5
```
Traceback (most recent call last):
  File "./specgen6.py", line 51, in <module>
    from libgroups import Grouping
  File "/cygdrive/c/prog/specgen/libgroups.py", line 25, in <module>
    from igraph import *
  File "build/bdist.cygwin-1.7.28-x86_64/egg/igraph/__init__.py", line 34, in <module>
  File "build/bdist.cygwin-1.7.28-x86_64/egg/igraph/_igraph.py", line 7, in <module>
  File "build/bdist.cygwin-1.7.28-x86_64/egg/igraph/_igraph.py", line 6, in __bootstrap__
ImportError: No such file or directory
``` 
This seems to be reported in http://lists.gnu.org/archive/html/igraph-help/2013-04/msg00100.html but I can't figure out if it's fixed.

I even tried with the 0.7 nightlies but got missing subdirs .deps, eg make fails with
```
lapack/.deps/liblapack_la-iladlr.Plo: No such file or directory
```

Please help!!

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/python-igraph#11
