### ISSUE TITLE
Running the test suite with an address sanitizer

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#884]
I built igraph with clang's address sanitizer and `-O0 -fno-inline -fno-omit-frame-pointer` and ran the test suite.  Other than test 32 & 33 (see #864), the two tests below failed. I'm attaching the address sanitizer output.

Both problems are related to igraph's cleanup mechanism. I'm not familiar enough with this to be able to decide whether these are false positives or not.

### Test 128

```
+==23926==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60600000c180 at pc 0x00010ca938d8 bp 0x7fff533b3490 sp 0x7fff533b3488
+READ of size 8 at 0x60600000c180 thread T0
+    #0 0x10ca938d7 in igraph_vector_ptr_pop_back vector_ptr.c:331
+    #1 0x10cd26309 in igraph_i_lad_solve lad.c:1429
+    #2 0x10cd25dad in igraph_i_lad_solve lad.c:1409
+    #3 0x10cd25dad in igraph_i_lad_solve lad.c:1409
+    #4 0x10cd2766a in igraph_subisomorphic_lad lad.c:1571
+    #5 0x10c84b386 in main (/Users/szhorvat/Repos/igraph-c/tests/testsuite.dir/128/./itest+0x100001386)
+    #6 0x7fff9d7225ac in start (/usr/lib/system/libdyld.dylib+0x35ac)
+    #7 0x0  (<unknown module>)
+
+0x60600000c180 is located 0 bytes to the right of 64-byte region [0x60600000c140,0x60600000c180)
+allocated by thread T0 here:
+    #0 0x10dca1d17 in wrap_realloc (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x42d17)
+    #1 0x10ca92edb in igraph_vector_ptr_reserve vector_ptr.c:224
+    #2 0x10ca935c6 in igraph_vector_ptr_push_back vector_ptr.c:317
+    #3 0x10cd2431c in igraph_i_lad_solve lad.c:1343
+    #4 0x10cd25dad in igraph_i_lad_solve lad.c:1409
+    #5 0x10cd2766a in igraph_subisomorphic_lad lad.c:1571
+    #6 0x10c84b386 in main (/Users/szhorvat/Repos/igraph-c/tests/testsuite.dir/128/./itest+0x100001386)
+    #7 0x7fff9d7225ac in start (/usr/lib/system/libdyld.dylib+0x35ac)
+    #8 0x0  (<unknown module>)
+
+SUMMARY: AddressSanitizer: heap-buffer-overflow vector_ptr.c:331 igraph_vector_ptr_pop_back
+Shadow bytes around the buggy address:
+  0x1c0c000017e0: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
+  0x1c0c000017f0: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
+  0x1c0c00001800: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
+  0x1c0c00001810: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
+  0x1c0c00001820: fd fd fd fd fa fa fa fa 00 00 00 00 00 00 00 00
+=>0x1c0c00001830:[fa]fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
+  0x1c0c00001840: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
+  0x1c0c00001850: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
+  0x1c0c00001860: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
+  0x1c0c00001870: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
+  0x1c0c00001880: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
+Shadow byte legend (one shadow byte represents 8 application bytes):
+  Addressable:           00
+  Partially addressable: 01 02 03 04 05 06 07 
+  Heap left redzone:       fa
+  Heap right redzone:      fb
+  Freed heap region:       fd
+  Stack left redzone:      f1
+  Stack mid redzone:       f2
+  Stack right redzone:     f3
+  Stack partial redzone:   f4
+  Stack after return:      f5
+  Stack use after scope:   f8
+  Global redzone:          f9
+  Global init order:       f6
+  Poisoned by user:        f7
+  Container overflow:      fc
+  Array cookie:            ac
+  Intra object redzone:    bb
+  ASan internal:           fe
+  Left alloca redzone:     ca
+  Right alloca redzone:    cb
+==23926==ABORTING
```

### Test 221

```
+==25989==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff5202e510 at pc 0x00010dc0ac8c bp 0x7fff5202e3d0 sp 0x7fff5202e3c8
+READ of size 4 at 0x7fff5202e510 thread T0
+    #0 0x10dc0ac8b in igraph_vs_destroy iterators.c:489
+    #1 0x10dcb9054 in IGRAPH_FINALLY_FREE igraph_error.c:201
+    #2 0x10dcb8f7a in igraph_error_handler_ignore igraph_error.c:152
+    #3 0x10dcb8b5d in igraph_error igraph_error.c:111
+    #4 0x10df3ce7d in igraph_ecumulative_proportionate_values microscopic_update.c:148
+    #5 0x10df40f41 in igraph_moran_process microscopic_update.c:804
+    #6 0x10dbd162c in error_tests (/Users/szhorvat/Repos/igraph-c/tests/testsuite.dir/221/./itest+0x10000162c)
+    #7 0x10dbd1d13 in main (/Users/szhorvat/Repos/igraph-c/tests/testsuite.dir/221/./itest+0x100001d13)
+    #8 0x7fff9d7225ac in start (/usr/lib/system/libdyld.dylib+0x35ac)
+    #9 0x0  (<unknown module>)
+
+Address 0x7fff5202e510 is located in stack of thread T0 at offset 80 in frame
+    #0 0x10df3c72f in igraph_ecumulative_proportionate_values microscopic_update.c:103
+
+  This frame has 2 object(s):
+    [32, 72) 'A' <== Memory access at offset 80 overflows this variable
+    [112, 136) 'es'
+HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
+      (longjmp and C++ exceptions *are* supported)
+SUMMARY: AddressSanitizer: stack-buffer-overflow iterators.c:489 igraph_vs_destroy
+Shadow bytes around the buggy address:
+  0x1fffea405c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405c60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405c90: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 00
+=>0x1fffea405ca0: 00 f2[f2]f2 f2 f2 00 00 00 f3 f3 f3 f3 f3 f3 f3
+  0x1fffea405cb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405cc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+  0x1fffea405cf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
+Shadow byte legend (one shadow byte represents 8 application bytes):
+  Addressable:           00
+  Partially addressable: 01 02 03 04 05 06 07 
+  Heap left redzone:       fa
+  Heap right redzone:      fb
+  Freed heap region:       fd
+  Stack left redzone:      f1
+  Stack mid redzone:       f2
+  Stack right redzone:     f3
+  Stack partial redzone:   f4
+  Stack after return:      f5
+  Stack use after scope:   f8
+  Global redzone:          f9
+  Global init order:       f6
+  Poisoned by user:        f7
+  Container overflow:      fc
+  Array cookie:            ac
+  Intra object redzone:    bb
+  ASan internal:           fe
+  Left alloca redzone:     ca
+  Right alloca redzone:    cb
+==25989==ABORTING
```

**Comment by ntamas** [comment]
Test 128 is not a false positive; it is shown by Valgrind as well. I have to check test 221, but I don't think it's a false positive either.
